"""Production settings."""
from .base import *  # noqa: F401,F403
from .base import SIMPLE_JWT, PLATFORM_JWT


DEBUG = False

SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

SIMPLE_JWT['AUTH_COOKIE_SECURE'] = True
PLATFORM_JWT['AUTH_COOKIE_SECURE'] = True
